name: Producer (Artifact Demo)

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate demo output (simulated)
        run: |
          mkdir -p out
          echo "Build ID: $GITHUB_RUN_ID" > out/report.txt
          echo "Timestamp: $(date -u)"   >> out/report.txt
          zip -jr demo-bundle.zip out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-bundle
          path: demo-bundle.zip
          retention-days: 7
